# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.137.0/containers/go/.devcontainer/base.Dockerfile
ARG VARIANT="1"
FROM hewenyulucky/gobuild:1.14

ENV GOPROXY=https://goproxy.cn,direct